### ISSUE TITLE
Missing git tag for v0.2.0

### ISSUE THREAD

**Issue by jontze** [boozook/mdbook-svgbob#20]
Thanks for your work and the cool project! :)

I just recognized that the git tag is missing for the already on crates.io released v0.2.0 version and therefore also the precompiled binaries that you normally build and attach to a github release.

I would really appreciate this, as to fetch the binaries from the github release is a fast way to install the plugin (especially in the CI) without going through the rust compilation process.

**Comment by boozook** [comment]
Thank you so much! ❤️
I'll do it soon, but before I have to update & test CI release pipeline - it seems broken. Couple days.

**Comment by boozook** [comment]
@jontze,
Done. [0.2](https://github.com/boozook/mdbook-svgbob/releases/tag/v0.2.0), [0.2.1](https://github.com/boozook/mdbook-svgbob/releases/tag/v0.2.1).
