### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by elasticdotventures** [boozook/mdbook-svgbob#7]
attempted to update some of the libraries in Cargo.toml to latest versions .. specifically:
 [dependencies]
-mdbook = "0.3"
-svgbob = "0.4"
-svg = "0.7"
+mdbook = "0.4.18"
+svgbob = "0.6.6"
+svg = "0.10.0"
 
-clap = "2.33"
+clap = "3.1.18"
 log = "0.4"
-env_logger = "0.7"
-semver = "0.9.0"
+env_logger = "0.9.0"
+semver = "1.0.9"
 
 toml = "0.5"
 serde = "1.0"
 serde_json = "1.0"
-pulldown-cmark = "0.7"
-pulldown-cmark-to-cmark = "3.0"
+pulldown-cmark = "0.9.1"
+pulldown-cmark-to-cmark = "10.0.1"

 --- 
 errors generated:

   Compiling mdbook-svgbob v0.1.1 (/home/xxx/fungiblefarm-dots/mdbook-svgbob)
error[E0432]: unresolved import `pulldown_cmark_to_cmark::fmt::cmark`
  --> src/preprocessor.rs:70:6
   |
70 |     use pulldown_cmark_to_cmark::fmt::cmark;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `cmark` in `fmt`

error[E0432]: unresolved import `svgbob::Grid`
 --> src/svgbob.rs:5:5
  |
5 | use svgbob::Grid;
  |     ^^^^^^^^^^^^ no `Grid` in the root

error[E0603]: module `fmt` is private
  --> src/preprocessor.rs:70:31
   |
70 |     use pulldown_cmark_to_cmark::fmt::cmark;
   |                                  ^^^ private module
   |
note: the module `fmt` is defined here
  --> /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/pulldown-cmark-to-cmark-10.0.1/src/lib.rs:5:5
   |
5  |     fmt,
   |     ^^^

warning: use of deprecated struct `clap::App`: Replaced with `Command`
  --> src/main.rs:10:12
   |
10 | use clap::{App, Arg, ArgMatches, SubCommand};
   |            ^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: use of deprecated struct `clap::SubCommand`: Replaced with `Command::new` unless you intended the `Subcommand` trait
  --> src/main.rs:10:34
   |
10 | use clap::{App, Arg, ArgMatches, SubCommand};
   |                                  ^^^^^^^^^^

warning: use of deprecated struct `clap::App`: Replaced with `Command`
  --> src/main.rs:28:5
   |
28 |     Ok(App::new(NAME).version(VERSION)
   |        ^^^

warning: use of deprecated struct `clap::SubCommand`: Replaced with `Command::new` unless you intended the `Subcommand` trait
  --> src/main.rs:32:9
   |
32 |            SubCommand::with_name("supports")
   |            ^^^^^^^^^^

error[E0107]: this struct takes 0 lifetime arguments but 1 lifetime argument was supplied
  --> src/main.rs:25:29
   |
25 | pub fn init_cli() -> Result<ArgMatches<'static>> {
   |                             ^^^^^^^^^^--------- help: remove these generics
   |                             |
   |                             expected 0 lifetime arguments
   |
note: struct defined here, with 0 lifetime parameters
  --> /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.18/src/parse/matches/arg_matches.rs:70:12
   |
70 | pub struct ArgMatches {
   |            ^^^^^^^^^^

Some errors have detailed explanations: E0107, E0432, E0603.
For more information about an error, try `rustc --explain E0107`.
warning: `mdbook-svgbob` (bin "mdbook-svgbob") generated 4 warnings
error: could not compile `mdbook-svgbob` due to 4 previous errors; 4 warnings emitted

**Comment by elasticdotventures** [comment]
🤔
unresolved import `pulldown_cmark_to_cmark::fmt::cmark`
no `cmark` in `fmt`rustc[E0432](https://doc.rust-lang.org/error-index.html#E0432)

https://github.com/Byron/pulldown-cmark-to-cmark/blob/main/CHANGELOG.md

**Comment by elasticdotventures** [comment]
taking a step back, and going to try to submit one patch at a time.

**Comment by boozook** [comment]
Thanks. Closed by 900cd776bc0bc2dd52587720e29f6acec61d4e66.
